version: '3.8'
services:
  database:
    image: 'postgres:14-alpine'
    container_name: 'parserdatabase'
    environment:
      - 'POSTGRES_DB=parserdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '8081:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'